### ISSUE TITLE
api+analyzer: Support height based queries

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/nexus#116]
##### SUMMARY

We initially planned on using Cockroach DB's [feature](https://www.cockroachlabs.com/docs/stable/as-of-system-time.html) to query the DB for the state at a historical block height (inferred from the processing time of said block).

We likely want to view past balances.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

API/Analyzer

##### ADDITIONAL INFORMATION

Would this conflict with parallel indexing?

**Comment by mitjat** [comment]
Major caveats on using cockroachDB time-travel for this:
- limited in how far back we can go; the [default is 25h](https://www.cockroachlabs.com/docs/stable/as-of-system-time.html), which is orders of magnitude different from what we need
- cockrach allows querying at any given _system_ time, which does not linearly correlate to block height -- if we index blocks out of order, or if we restore the rows from a DB dump (which groups statements by sql table, not by blockchain height), the time-travel results will be trash
