### ISSUE TITLE
analyzer: Support for historical aggregate data

### ISSUE THREAD

**Issue by ennsharma** [oasisprotocol/nexus#133]
##### SUMMARY
As of #132 we can collect time series data about blocks, transactions, and events. This is easy to do with materialized views since by storing blocks and transactions we are naturally persisting historical data from which aggregates can be constructed.

However, for other types of time series data such as:
- total escrow at a given point in time
- total number of delegators at a given point in time
- total stake held by validator with the most stake at a given point in time

We are unable to do this as we store _current_ data for staking, registry, governance, etc. backends. We must collect this data during the indexing process, and this can be done via a `checkpointWorker` that runs every k processed blocks and computes an aggregate data point for every additional time series we want.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`storage` `analyzer`

**Comment by ptrus** [comment]
For validator staking history this was done in https://github.com/oasisprotocol/nexus/pull/703 
For other types of data this is currently not planned.
