### ISSUE TITLE
revisit dummy runtime argument for consensus-only QueryFactory

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/nexus#199]
We could just pass "consensus" here, if you feel that obviates the comment. It will also make debugging easier in case we do use the runtime identifier somewhere accidentally, because "consensus" is easier to spot than "".

_Originally posted by @mitjat in https://github.com/oasisprotocol/oasis-indexer/pull/190#discussion_r1001356208_

**Comment by ptrus** [comment]
References code that i believe no longer exists.
