### ISSUE TITLE
range filters: make one side exclusive?

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/nexus#203]
That's my understanding of how times work too, yes. Tricky to describe the behavior correctly and succinctly ...

WDYT about changing the queries to be inclusive on the lower limit and exclusive on the upper? (i.e. `>=` and `<`)
That would make times behave naturally. And it would give us an API that is (in my experience) in line with most other range-related APIs (e.g. python slices). It also would make it easier to "scan" a range with multiple queries (e.g. fetching tx with fees from the interval `[A,B)`, then from `[B,C)`, etc; not that I have a great use case for that :).

_Originally posted by @mitjat in https://github.com/oasisprotocol/oasis-indexer/issues/200#issuecomment-1289617939_

**Comment by ptrus** [comment]
No need for now. Explorer frontend is fine with inclusive filters.
