### ISSUE TITLE
Add prometheus metrics + grafana charts for node latency

### ISSUE THREAD

**Issue by mitjat** [oasisprotocol/nexus#205]
Indexer speed (esp. when reindexing) depends on node responsiveness a lot. Instrument calls (`GetBlock()`, `GetEvents()`, etc) in `storage/oasis/{consensus,runtime}.go` to measure how long the node takes to respond, and plot them in grafana.

**Comment by mitjat** [comment]
https://app.clickup.com/t/3ufk8kr

**Comment by ptrus** [comment]
The existing blockfetch metrics are sufficient at this time:
https://github.com/oasisprotocol/nexus/blob/12a1ea7e900205d33f647b36574a623ec2057009/analyzer/consensus/consensus.go#L332
https://github.com/oasisprotocol/nexus/blob/12a1ea7e900205d33f647b36574a623ec2057009/analyzer/runtime/runtime.go#L191
