### ISSUE TITLE
Do not choke on malformed consensus txs

### ISSUE THREAD

**Issue by mitjat** [oasisprotocol/nexus#209]
Currently, if the indexer encounters a block with a malformed-cbor consensus tx, it will [error out of processing that block](https://github.com/oasisprotocol/oasis-indexer/blob/305095e8b1c04916924b517eeca4405d97586a90/storage/oasis/consensus.go#L86-L86) and will keep retrying it forever.
Txs in a block are not necessarily well-formed CBOR. Malformed txs will be rejected at the consensus layer, sure, but they can still be in a proposed block. Source: [Jernej on Slack](https://oasis-labs.slack.com/archives/CHTNKCRL0/p1667235927746099?thread_ts=1667235517.937429&cid=CHTNKCRL0)

More Jernej wisdom:
- In consensus, the returned transactions are sorted by index, you can just use that in the indexer if needed
- In the runtime, a duplicate tx _within a block_ is not possible as transactions are keyed by hash (this is a leftover of our previous multi-committee-mergable design). Honest proposers will also not include transactions that fail nonce checks, so these (duplicate txs in general) should be rare, but note that in pre-Damask Emerald this was not the case. We could even forbid those in the future.
- A proposed paratime round will never contain a tx that is invalid cbor

**Comment by kostko** [comment]
> In the runtime such a situation (= with malformed txs, presumably) is not possible as transactions are keyed by hash (this is a leftover of our previous multi-committee-mergable design)

There are two things for runtimes based on our SDK: there can be no duplicate transactions within a block and also there can be no malformed (or failing signature verification) transactions in a block.

**Comment by mitjat** [comment]
https://app.clickup.com/t/3ua54a7

**Comment by ptrus** [comment]
This was addressed (evidently by the fact that Nexus is not stuck).
