### ISSUE TITLE
Emerald: additional token standards

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/nexus#225]
currently we only have ERC-20

**Comment by mitjat** [comment]
Example of where we want to expose this: https://github.com/oasisprotocol/oasis-indexer/pull/224#discussion_r1030922644

**Comment by pro-wh** [comment]
discussion related to querying other standards' metadata:

https://github.com/oasisprotocol/oasis-indexer/pull/229#discussion_r1043387086

https://github.com/oasisprotocol/oasis-indexer/pull/229#discussion_r1043390224

**Comment by pro-wh** [comment]
https://github.com/oasisprotocol/oasis-indexer/pull/284#discussion_r1083006875

**Comment by pro-wh** [comment]
https://app.clickup.com/t/866age7bv ticket for ERC-721 support

**Comment by ptrus** [comment]
ERC-721 support was added. For other token standards new issues can be opened.
