### ISSUE TITLE
Implement statecheck for Emerald

### ISSUE THREAD

**Issue by mitjat** [oasisprotocol/nexus#240]
Do one or both of the following:
- expand `genesis_test` so it covers emerald state as well. This requires a new-ish method in the `accounts` SDK module that dumps the state of all accounts (`get_all_balances()` exists but is not exposed as an RPC).
- mark addresses that are involved in emerald txs as dirty, then have a separate analyzer that periodically goes and checks the balances of dirty addresses against the node (by querying balances of individual addresses).

Let's prioritize the first option because it's more thorough. In particular, assume the hypothetical indexer bug is of the kind where we fail to parse an affected account from a tx or event. Then the account's balance will be changed (that's what I mean by "affected") in evm but we'll never mark it as dirty, so we'll never find that discrepancy. 

The second options is also needed because it's probably the only way to get (partial) visibility into ERC20 (and other ERC) balances. Those are potentially arbitrary smart contracts that expose a limited API, `getAllBalances` or equivalent not being one of the available methods.

**Comment by ptrus** [comment]
This was done #319
