### ISSUE TITLE
More descriptive errors in storage client

### ISSUE THREAD

**Issue by Andrew7234** [oasisprotocol/nexus#245]
The methods in [storage client](https://github.com/oasisprotocol/oasis-indexer/blob/main/storage/client/client.go) currently only return `common.ErrStorageError` when something goes wrong. It'd be better to return more descriptive errors.

Currently, [api/common/errors](https://github.com/oasisprotocol/oasis-indexer/blob/main/api/common/errors.go) contains all the indexer error types. We could expand this to include more error types, and/or extend this into wrappable error classes. Suggestions/alternatives are welcome.

**Comment by ptrus** [comment]
This was addressed in https://github.com/oasisprotocol/nexus/pull/297 (ErrStorageError now propagates some errors)
