### ISSUE TITLE
Use values > uint64 during testing

### ISSUE THREAD

**Issue by Andrew7234** [oasisprotocol/nexus#248]
#236 added support for balance-y values larger than uint64. It would be nice to test this in the oasis-test-runner e2e tests. This requires modifying [this function](https://github.com/oasisprotocol/oasis-core/blob/go/v0.2202.3/go/oasis-node/cmd/debug/txsource/workload/workload.go#L162) in oasis-core to use `quantity.Quantity` and permit configurable transfer amounts.

**Comment by ptrus** [comment]
This is tested in the E2E regression tests.
