### ISSUE TITLE
Implement `size`, `gas_used` for blocks

### ISSUE THREAD

**Issue by mitjat** [oasisprotocol/nexus#260]
These properties are neither collected nor exposed via our API yet.

Requirement for Explorer MVP.

**Comment by Andrew7234** [comment]
Not sure if this ticket was for consensus or emerald, but @pro-wh implemented this for emerald blocks in https://github.com/oasisprotocol/oasis-indexer/pull/190

I'd vote to update this ticket to be specifically for consensus.

**Comment by ptrus** [comment]
This was done for paratimes and consensus.
