### ISSUE TITLE
custom postgres serialization for BigInt (and other custom types)

### ISSUE THREAD

**Issue by mitjat** [oasisprotocol/nexus#274]
We curerntly have to manually convert non-primitive types to suitable primitive types before passing them to postgres. Exanmple: #272 and BigInt. This is error-prone. Check what is required by our db library to convert types automatically.

IIRC the customization might need to be particularly verbose when there's a custom type on the postgres side also (such as our `UINT_NUMERIC`).

**Comment by ptrus** [comment]
This was done in https://github.com/oasisprotocol/nexus/pull/297
