### ISSUE TITLE
Analyzer that pulls ROSE valuations, API that exposes them

### ISSUE THREAD

**Issue by mitjat** [oasisprotocol/nexus#291]
The frontend currently pulls ROSE valuations from CoinGecko directly, but sooner or later we'll hit their rate limits.

Instead, the indexer should pull from CoinGecko (or other similar service) using a new analyzer, store the result in a new table, and serve the timeline of valuations in a new endpoint.

**Bonus:** Alter the DB wiping method (`DANGER__WIPE_STORAGE_ON_STARTUP`) so it does _not_ erase historic valuations. Publicly accessible historical valuations usually only have daily granularity, whereas we can pull and store with much higher frequency (e.g. once every 5 minutes, or even every minute).

Suggested available output granularities: 5 min and 1 day (like `/tx_volume` endpoint).

**Comment by ptrus** [comment]
It was decided that it is more suitable to fetch this from frontend.
