### ISSUE TITLE
Fetch validators by address

### ISSUE THREAD

**Issue by Andrew7234** [oasisprotocol/nexus#334]
The current indexer api only supports fetching by entityID, which might be harder for users to derive. This ticket should be revisited when implementing the consensus part of Oasis Explorer

For reference, oasisscan uses [consensus address](https://www.oasisscan.com/validators/detail/oasis1qq3xrq0urs8qcffhvmhfhz4p0mu7ewc8rscnlwxe) too

**Comment by ptrus** [comment]
This was implemented.
