### ISSUE TITLE
Add timestamp to runtime events

### ISSUE THREAD

**Issue by csillag** [oasisprotocol/nexus#468]
##### SUMMARY
We would like to know the time and date when the runtime events have occurred.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Hopefully, only `api`.

##### ADDITIONAL INFORMATION

When displaying "token transfers" for an account, we are listing the events, and we would also like to display the time when these events have happened, similarly to this view: https://explorer.sapphire.oasis.io/address/0x643c8A8120eFB675E82C5C58d8D473f5aDd0B5e6/token-transfers

**Comment by Andrew7234** [comment]
Implemented in https://github.com/oasisprotocol/nexus/pull/491
