### ISSUE TITLE
what are the steps to fix the issue

### ISSUE THREAD

**Issue by PazhaniMani** [oasisprotocol/nexus#536]
pcodeindia@Pcodes-MacBook-Air GoBackend % go run .
# github.com/oasisprotocol/nexus/api/v1/types
api/v1/types/util.go:16:9: undefined: ConsensusEventType
api/v1/types/util.go:18:7: undefined: ConsensusEventTypeStakingTransfer
api/v1/types/util.go:19:3: undefined: ConsensusEventTypeStakingBurn
api/v1/types/util.go:20:3: undefined: ConsensusEventTypeStakingEscrowAdd
api/v1/types/util.go:21:3: undefined: ConsensusEventTypeStakingEscrowTake
api/v1/types/util.go:22:3: undefined: ConsensusEventTypeStakingEscrowDebondingStart
api/v1/types/util.go:23:3: undefined: ConsensusEventTypeStakingEscrowReclaim
api/v1/types/util.go:42:9: undefined: Layer
api/v1/types/util.go:51:9: undefined: Runtime
api/v1/types/util.go:61:10: undefined: GetLayerStatsActiveAccountsParams
api/v1/types/util.go:23:3: too many errors
pcode@Pcodes-MacBook-Air GoBackend %  

how to fix it

**Comment by PazhaniMani** [comment]
How To Fix the issue

**Comment by mitjat** [comment]
You're missing the Go types that are autogenerated from the OpenAPI spec (`v1.yaml`).
See the `Makefile`. The best way to build locally is `make nexus`, as is also described in the top-level README.

**Comment by PazhaniMani** [comment]
I am a beginner for nexus and go lang, so please elaborate the step by step guide

**Comment by pro-wh** [comment]
run `make nexus` instead of `go build .`

**Comment by PazhaniMani** [comment]
pcode@Pcodes-MacBook-Air GoBackend % make nexus
fatal: No names found, cannot describe anything.
bash: oapi-codegen: command not found
ERROR: Installed oapi-codegen is not v1.12.x. See Makefile.
go: updates to go.mod needed; to update it:
        go mod tidy
cannot locate oapi-codegen templates dir
make: *** [codegen-go] Error 1

**Comment by pro-wh** [comment]
oh shoot yeah, we don't have any docs about setting up the openapi tools
