### ISSUE TITLE
How to setup in local step by step guide 

### ISSUE THREAD

**Issue by PazhaniMani** [oasisprotocol/nexus#541]
Hi Team,
I am learning to new go language, so please help this project, I already setup this project but **error like this:**
pcode@Pcodes-MacBook-Air GoBackend % go run .
# github.com/oasisprotocol/nexus/api/v1/types
api/v1/types/util.go:16:9: undefined: ConsensusEventType
api/v1/types/util.go:18:7: undefined: ConsensusEventTypeStakingTransfer
api/v1/types/util.go:19:3: undefined: ConsensusEventTypeStakingBurn
api/v1/types/util.go:20:3: undefined: ConsensusEventTypeStakingEscrowAdd
api/v1/types/util.go:21:3: undefined: ConsensusEventTypeStakingEscrowTake
api/v1/types/util.go:22:3: undefined: ConsensusEventTypeStakingEscrowDebondingStart
api/v1/types/util.go:23:3: undefined: ConsensusEventTypeStakingEscrowReclaim
api/v1/types/util.go:42:9: undefined: Layer
api/v1/types/util.go:51:9: undefined: Runtime
api/v1/types/util.go:61:10: undefined: GetLayerStatsActiveAccountsParams
api/v1/types/util.go:23:3: too many errors
pcode@Pcodes-MacBook-Air GoBackend % 

How to resolve this issue plz help me.........

**Comment by pro-wh** [comment]
https://github.com/oasisprotocol/nexus#local-development see instructions here. you'll need to run `make nexus` and other commands instead of `go run .`

**Comment by PazhaniMani** [comment]
pcode@Pcodes-MacBook-Air GoBackend % make nexus
fatal: No names found, cannot describe anything.
bash: oapi-codegen: command not found
ERROR: Installed oapi-codegen is not v1.12.x. See Makefile.
go: updates to go.mod needed; to update it:
        go mod tidy
cannot locate oapi-codegen templates dir
make: *** [codegen-go] Error 1
pcode@Pcodes-MacBook-Air GoBackend %

**Comment by ptrus** [comment]
Please open a PR with suggested improvements.
