### ISSUE TITLE
runtime tx unexpected fields

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/nexus#704]
cc @matevz @csillag 

https://explorer.oasis.io/mainnet/sapphire/tx/7224d59e6b74d9b2caf55ab40dfe0757cef4f71c66d3a7aba3de1d267d2ea409

this tx has `error` set while the status is unknown. api should clear out the error

also its method is blank, which isn't right. allegedly it's supposed to be accounts.Transfer

**Comment by lukaw3d** [comment]
Looks like a successful tx to me: it emitted events, and did transfer ROSE

So:
- `status`: should be success
- `amount` / Value: should be 199.809878 ROSE
- `to_eth`: should be 0xAaF64683099cF03c69007fdD39b21e91a32d05be (tho this is a native (non-EVM) transfer?)

**Comment by pro-wh** [comment]
oh was this an encrypted transaction?

**Comment by lukaw3d** [comment]
Hm this tx is causing issues to oasisscan too
- https://www.oasisscan.com/ search finds this transaction by hash and redirects to it on sapphire
- it lists it in the round https://www.oasisscan.com/paratimes/000000000000000000000000000000000000000000000000f80306c9858e7279/round/3995186
- but it errors when opening the details https://www.oasisscan.com/paratimes/000000000000000000000000000000000000000000000000f80306c9858e7279/transactions/7224d59e6b74d9b2caf55ab40dfe0757cef4f71c66d3a7aba3de1d267d2ea409?round=3995186
- https://api.oasisscan.com/mainnet/runtime/transaction/info?id=000000000000000000000000000000000000000000000000f80306c9858e7279&hash=7224d59e6b74d9b2caf55ab40dfe0757cef4f71c66d3a7aba3de1d267d2ea409 err 500

**Comment by ptrus** [comment]
This is what oasis cli reports for the tx:


```
./cli paratime show 3995186 --paratime sapphire

=== Result of transaction 4 ===
Status: unknown
Data:
  {
    "data": "9e845df1c05276f79f67b2d2f8eb68bc516438a473",
    "nonce": "00000000003cf63100000004000000"
  }

=== Events emitted by transaction 4 ===
Events: 2

  --- Event 0 ---
  Module: accounts
  Code:   1
  Data:
    [
      {
        "Burn": null,
        "Mint": null,
        "Transfer": {
          "amount": {
            "Amount": {},
            "Denomination": ""
          },
          "from": "oasis1qqugfeelqtp3qaxhdrwfv9nhpvwckjxr7yk369p7",
          "to": "oasis1qzy0yk6hwxx7e236cmawlt7xukpn8avtqq6le3l8"
        }
      },
      {
        "Burn": null,
        "Mint": null,
        "Transfer": {
          "amount": {
            "Amount": {},
            "Denomination": ""
          },
          "from": "oasis1qqugfeelqtp3qaxhdrwfv9nhpvwckjxr7yk369p7",
          "to": "oasis1qp3r8hgsnphajmfzfuaa8fhjag7e0yt35cjxq0u4"
        }
      }
    ]

  --- Event 1 ---
  Module: core
  Code:   1
  Data:
    [
      {
        "amount": 12389
      }
    ]
```

**Comment by kostko** [comment]
Looks like an encrypted transaction, incorrectly interpreted by the explorer as plain?

**Comment by csillag** [comment]
Explorer recognizes encrypted transactions based on the presence of the `encryption_envelope` field, but here, we don't get one [from nexus](https://nexus.oasis.io/v1/sapphire/transactions/7224d59e6b74d9b2caf55ab40dfe0757cef4f71c66d3a7aba3de1d267d2ea409).

**Comment by csillag** [comment]
> oh was this an encrypted transaction?

Yes this was.

> edit: explorer says plain 👀

@pro-wh Yes it does, because Nexus is not including an `encryption_envelope`, which it usually does for encrypted TXs. Is there any chance to find out this reason for that?

**Comment by pro-wh** [comment]
should step through the analyzer on this tx

**Comment by Andrew7234** [comment]
Some early observations:
- The transaction [AuthProof module](https://github.com/oasisprotocol/oasis-sdk/blob/main/client-sdk/go/types/transaction.go#L40) is empty. Nexus expects this to be `evm.ethereum.v0` for eth transactions, for which it [extracts the eth hash](https://github.com/oasisprotocol/nexus/blob/main/analyzer/runtime/extract.go#L231).
- The sdk [Call.Method](https://github.com/oasisprotocol/oasis-sdk/blob/main/client-sdk/go/types/transaction.go#L365) is empty. Nexus currently [expects ](https://github.com/oasisprotocol/nexus/blob/main/analyzer/runtime/visitors.go#L37)this field to be populated, eg `evm.Call`

**Comment by kostko** [comment]
The above transaction is _not_ an Ethereum transaction (which is why the auth proofs are regular signatures).

It is an encrypted SDK transaction, see the above CLI dump. The method is empty as is the case with all non-Ethereum encrypted transactions. The actual method name is encrypted.

**Comment by pro-wh** [comment]
ok yeah this transaction style is intentional. we need something similar to EVMMaybeUnmarshalEncryptedData but for the oasis level of encryption
