### ISSUE TITLE
Should balance be equal to total received - total sent (± fees)?

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/nexus#705]
https://explorer.oasis.io/mainnet/sapphire/address/0xAaF64683099cF03c69007fdD39b21e91a32d05be
Balance: 0.4938682 ROSE
Total Received: 67,570.0348413 ROSE
Total Sent: 47,369.5409731 ROSE

The discrepancy does not look like negligible fees. Do we intentionally not count something that explains the difference? Maybe the diff is in transactions like https://github.com/oasisprotocol/nexus/issues/704

**Comment by lukaw3d** [comment]
https://explorer.oasis.io/mainnet/sapphire/address/0x4f1DAE99883E44c924Db37e4B537Da87A7459029
Balance: 0
Total Received: 0 ROSE
Total Sent: 200 ROSE

First tx involving this account https://explorer.oasis.io/mainnet/sapphire/tx/0x6a9c99753a859d508afb826a60b4f2a6153a50d167db0583cd158213b0184978 is receiving 200 ROSE

**Comment by pro-wh** [comment]
> First tx involving this account https://explorer.oasis.io/mainnet/sapphire/tx/0x6a9c99753a859d508afb826a60b4f2a6153a50d167db0583cd158213b0184978 is receiving 200 ROSE, but it didn't emit an event?

maybe it was an evm transfer?

**Comment by lukaw3d** [comment]
> > First tx involving this account https://explorer.oasis.io/mainnet/sapphire/tx/0x6a9c99753a859d508afb826a60b4f2a6153a50d167db0583cd158213b0184978 is receiving 200 ROSE, but it didn't emit an event?
> 
> maybe it was an evm transfer?

Oh it's evm.call with is_likely_native_token_transfer
https://lukaw3d.github.io/oasis-indexer-simple-frontend/production-mainnet/#/sapphire/transactions/6a9c99753a859d508afb826a60b4f2a6153a50d167db0583cd158213b0184978

**Comment by lukaw3d** [comment]
And the difference in https://explorer.oasis.io/mainnet/sapphire/address/0xAaF64683099cF03c69007fdD39b21e91a32d05be is also from evm.calls with is_likely_native_token_transfer, mainly
https://lukaw3d.github.io/oasis-indexer-simple-frontend/production-mainnet/#/sapphire/transactions/2b3849555428a443deea0e77edeaee84ac735d10ef40ccdb034da72d041f9819

**Comment by pro-wh** [comment]
ugh our output spec is so muddied

**Comment by lukaw3d** [comment]
Another cause of inconsistency (copied from https://app.clickup.com/t/8693rpyxe)

https://explorer.dev.oasis.io/mainnet/sapphire/address/0x0A400fb7b16760fF1ed77192cFE45cC303BcB980
> Balance: 3.498878043032296773 ROSE
> Total Received: 0 ROSE
> Total Sent: 0 ROSE

Account created and funded by a contract (payable transfer) - probably by authzn https://github.com/oasisprotocol/demo-authzn/blob/a91f8fd623e8d89f49b0dd56a61792cbc2b7e0fa/backend/contracts/Account.sol#L89-L94 or https://github.com/oasisprotocol/demo-authzn/blob/a91f8fd623e8d89f49b0dd56a61792cbc2b7e0fa/backend/contracts/WebAuthNExample.sol#L56-L62

https://explorer.oasis.io/mainnet/sapphire/address/oasis1qzlpjg6u20quj063tnkp755fq8wqs27x0gcxq382
> Balance: 6.057102191090756501 ROSE
> Total Received: 0 ROSE
> Total Sent: 0 ROSE

This account was created and funded by an Illuminex smart contract

**Comment by lukaw3d** [comment]
From meeting:
- frontend will stop showing these
- backend api spec will mark them inaccurate / deprecated
