### ISSUE TITLE
analyzer: Get information about block proposers and signatures

### ISSUE THREAD

**Issue by ennsharma** [oasisprotocol/nexus#74]
##### SUMMARY
We can get information about a block proposer and signatures for a commit from Tendermint's [`BlockMeta`](https://pkg.go.dev/github.com/oasisprotocol/oasis-core/go@v0.2201.7/consensus/tendermint/api#BlockMeta). Our [`Block.Meta`](https://pkg.go.dev/github.com/oasisprotocol/oasis-core/go/consensus/api#Block) will deserialize into this.

This is tracked by both Oasis Scan and Oasis Monitor.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`analyzer`

##### ADDITIONAL INFORMATION
It may be a useful feature for tracking uptime metrics for our wallets. We can check how many of the last k blocks were signed by the validator in question.

**Comment by mitjat** [comment]
While this is nice data to have indexed away, the primary/only user-facing feature based on this is node uptime (#64), for Explorer list of nodes and for Wallet suggested escrow holders.

**Comment by ptrus** [comment]
This has been implemented in https://github.com/oasisprotocol/nexus/pull/646
