### ISSUE TITLE
Cloudflare timeout errors don't return CORS headers

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/nexus#743]
Related to https://github.com/oasisprotocol/nexus/pull/733

If nexus doesn't respond, then Cloudflare returns a timeout error, and it is missing CORS headers
(open https://explorer.dev.oasis.io/mainnet/sapphire/address/0x8Bc2B030b299964eEfb5e1e0b36991352E56D2D3/events#events, wait 100 seconds, https://nexus.oasis.io/v1/sapphire/events?limit=10&offset=0&rel=oasis1qpdgv5nv2dhxp4q897cgag6kgnm9qs0dccwnckuu fails with 524, frontend is not allowed to read the error code)

Low priority: it rarely happens, and frontend now does show an error in these cases https://github.com/oasisprotocol/explorer/pull/1513

**Comment by lukaw3d** [comment]
@uscinski says an easy solution is to put a smaller timeout on nexus

**Comment by ptrus** [comment]
Will be fixed via https://github.com/oasisprotocol/nexus/pull/821 and https://github.com/oasisprotocol/nexus/pull/849
