### ISSUE TITLE
Add Localnet chain support

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/nexus#753]
During the hackathons, we get a common request to have some kind of an explorer available to debug the transactions etc. Because of Oasis specifics and with the occurrence of ROFL, other explorers became infeasible.

We should enable people to run a complete Oasis Explorer locally (inside a docker image?) that connects to the sapphire-localnet or emerald-localnet images and indexes the chain. This should also include the Explorer's frontend.

Depends on https://github.com/oasisprotocol/oasis-web3-gateway/issues/423

**Comment by ptrus** [comment]
This was done https://github.com/oasisprotocol/oasis-web3-gateway/pull/637
