### ISSUE TITLE
Add validator name to delegations/debonding_delegations endpoints

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/nexus#779]
<div class="ql-block" data-block-id="block-5fbaf8ae-a662-4485-bffc-24fc9025d6ab">Currently we only return the entity ID to represent a validator for some endpoints, mainly the delegations/debonding delegations: <a class="ql-link" href="https://testnet.nexus.oasis.io/v1/consensus/accounts/oasis1qrfzje4yzruzayezpdc79fhsaul4lshwyqyy2gvu/delegations?limit=5&amp;offset=0" rel="noopener noreferrer" target="_blank">https://testnet.nexus.oasis.io/v1/consensus/accounts/oasis1qrfzje4yzruzayezpdc79fhsaul4lshwyqyy2gvu/delegations?limit=5&amp;offset=0</a></div><div class="ql-block" data-block-id="block-5aa475d9-6617-4409-8cf3-91541ecec43e"><br></div><div class="ql-block" data-block-id="block-5c866415-aadf-4d88-92b9-5297612b9ad0">Request from frontend: Add the validator name when available to the api responses</div>

---
Comment from @buberdds:

<p>Hey <a href="javascript: void;" data-test="mention" class="cu-mention   " data-user="42320508" data-user-theme-color="#7f77f1" data-name="Andrew Low" data-updated="true"><code>@</code>Andrew Low</a>, now when I think about it I think we need something more.</p><p class="ql-linebreak"><br></p><p><a data-link-card="true" href="https://explorer.dev.oasis.io/mainnet/consensus/address/oasis1qqnk4au603zs94k0d0n7c0hkx8t4p6r87s60axru?page=2" target="_blank">https://explorer.dev.oasis.io/mainnet/consensus/address/oasis1qqnk4au603zs94k0d0n7c0hkx8t4p6r87s60axru?page=2</a></p><p class="ql-linebreak"><br></p><p>Staking card (delegations API) validator column <code>oasis1…9eu2ev</code> </p><p>Transactions (transactions API) to column <code>oasis1…9eu2ev</code> </p><p class="ql-linebreak"><br></p><p>but in case of transactions API it doesn't make sense to add ValidatorMedia and check if any addr is in validators list.</p><p>This all could work with extending Named Account <code>account-names/mainnet_consensus.json</code> , but validator addresses can change so it cannot be hardcoded.</p><p class="ql-linebreak"><br></p><p><a href="javascript: void;" data-test="mention" class="cu-mention   " data-user="36510803" data-user-theme-color="#7f77f1" data-name="Peter" data-updated="true"><code>@</code>Peter</a> I remember you had some idea, but I don't remember details.  </p><p class="ql-linebreak"><br></p><p>side note: when designing solution let's keep in mind that long term it is not only about validators, but also ERC-20 and ERC-721 tokens names/addresses. Can these be hardcoded in <code>account-names</code> ?</p>

---
Comment from Peter:

<p>My idea would be to keep the APIs as they are, and on frontend, query the <code>ValidatorMedia</code>  for all validators once and then store/cache the responses locally in client store for some time (e.g. 5 minutes or until the page is refreshed). Then, on the frontend, whenever you are dealing with addresses, additionally check the local store to see if the address has a name and use it. </p><p class="ql-linebreak"><br></p><p>I have no idea how simple/hard this is to achieve in our frontend architecture, but to me, it seems a very logical solution and is general enough that I can also work for other types of named addresses (account names, token names...).</p>

---
Comment from @buberdds:

<p>ahh so just fetch all validators whenever we need it using<code>https://nexus.oasis.io/v1/consensus/validators</code>  and transform response to key/value map</p><p>other than that</p><ul class="ql-rendered-list-container" data-is-root="true"><li data-block-id="block-0761e6ab-c9fe-48d3-99a3-899cf4fc2f05" class="ql-rendered-bullet-list"><p>works until we hit 1000 validators</p></li><li data-block-id="block-17c4c5eb-2c85-43f7-96a3-82bd382dc1a2" class="ql-rendered-bullet-list"><p>different frontend logic compared to other account names</p></li><li data-block-id="block-565a9372-b7e6-4754-9a4a-3b6720847287" class="ql-rendered-bullet-list"><p>validators endpoint is slow (but caching response for a few minutes is fine here)</p></li></ul><p class="ql-linebreak"><br></p><p>This sounds good. Thanks will do it this way.</p>

---
Comment from @buberdds:

<p>What about tokens ERC-20 and ERC-721 tokens names/addresses? This cannot be fetched like validators because of is_total_count_clipped: true.</p>

---
Comment from Peter:

<blockquote data-block-id="block-02377030-fa61-4d28-8e8e-d62be2e5c8b0">different frontend logic compared to other account names</blockquote><p>Yeah different logic for fetching from API, but on the frontend I believe it can be unified so that on that end it would be the same.</p><p class="ql-linebreak"><br></p><blockquote data-block-id="block-5b1f4bf3-5717-4295-b824-febf48e7a532">validators endpoint is slow (but caching response for a few minutes is fine here)</blockquote><p>We can/should also look into improving the endpoint performance on the backend. But yeah even then we should still cache this on frontend as well.</p><p>Feel free to create a task for this it is problematic.</p><p class="ql-linebreak"><br></p><blockquote data-block-id="block-a578b043-2e24-4bf5-ae9c-e54b9a3691a1">What about tokens ERC-20 and ERC-721 tokens names/addresses? This cannot be fetched like validators because of is_total_count_clipped: true.</blockquote><p>I'm not familiar with that part of the API, how is it currently fetched? We can make the needed changes on the API to make it simpler/more convenient. </p>

**Comment by ptrus** [comment]
We decided against this: https://github.com/oasisprotocol/nexus/pull/769#discussion_r1810183223
