### ISSUE TITLE
api: performance benchmarking

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/nexus#81]
Related to caching work. We want to test the steady-state analyzer (= one that's not still actively catching up to the blockchain, but still invalidtes caches by producing a new block every 6s or so), which we can do in two ways:
- oasis-net-runner (unblocked by #142)
- a custom indexer that starts syncing only ~10k blocks behind blockchain head

Measure performance against parallel requests, etc

**Comment by mitjat** [comment]
Priority depends on how publicly we launch ...

**Comment by mitjat** [comment]
https://app.clickup.com/t/3u9y779

**Comment by ptrus** [comment]
API has been released and is usable publicly. Addressing performance issues is an ongoing process and there is no plan to add API performance benchmarks at this point.
