### ISSUE TITLE
Indexer: Set up testnet infra

### ISSUE THREAD

**Issue by csillag** [oasisprotocol/nexus#843]
Migrating issue from another platform

- [ ]     ndexer testnet: staging and prod DBs
- [ ]     testnet Sapphire oasis-client node
- [ ]     New public hostnames (e.g. [`index-testnet.oasislabs.com`](http://index-testnet.oasislabs.com) or similar; check what is most congruent with other oasis APIs)
- [ ]     archive testnet nodes accessible from `oasis-infra-{staging,production}` in GCP -- LOW PRIORITY

**Comment by ptrus** [comment]
This was done.
