### ISSUE TITLE
infra: Automate staging and release deploys

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/nexus#91]
##### SUMMARY
We should deploy the Indexer on a release.

##### ISSUE TYPE
- Feature Idea

**Comment by mitjat** [comment]
I suggest we deploy the Indexer:
- to prod when a github release is cut
- to staging on every merge into main

This is an aggressive schedule that doesn't let any single version of the indexer "mature and mellow" in staging so we could be fully convinced of its stability before pushing to prod, but it does let us see/test the results of our work fast. I think that's the right balance for this early in development. Once we're more public/stable, we'll want staging on release (or manual trigger), prod on manual trigger, and possibly a new dev environment that gets deployed into after every merge into main.

**Comment by aefhm** [comment]
Maybe we can add some more comments on reindexing and how that would affect this?

**Comment by mitjat** [comment]
https://app.clickup.com/t/3t22jh0

**Comment by mitjat** [comment]
I think reindexing is a separate can of worms. I have a cmdline flag in a local branch of mine that lets you trigger a reindex (= nuking the DB before start) without manual db fiddling. Which is fine for staging/dev maybe, but for prod, we'll probably want some sort of ops solution for a background reindex and then instant swap. And/or commit to only doing incremental reindexes. Either way, out of scope for this ticket, but something we should design eventually.

**Comment by ptrus** [comment]
The current process is sufficiently automated.
