### ISSUE TITLE
api: Improve pagination

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/nexus#95]
We want to improve/make pagination ordering work by at least some commonly used parameters.

TODO:
- [ ] look over Etherscan's implementation
- [ ] Get Product input

**Comment by mitjat** [comment]
Can you say more about the way(s) in which the current pagination mechanism is not ideal?

Here's an improvement I'd like to see:
> `offset` is not stable over time. Notably, it is not stable from the time we display a list of (e.g.) 20 latest blocks, to the time the user clicks "next page". If 20 new rounds have completed in the meantime, clicking "next page" will get the user the exact same set of blocks -- not what they expected, presumably.
> Better to have a continuation token here instead of an offset. The simplest continuation token is just the identifier of the last currently displayed block.

(first discussed/noticed in a [comment in the Explorer API doc](https://docs.google.com/document/d/1oSqo9TAYk3pv4KedS3p6DQ9WFZM_gfuMceaYQv6R2hk/edit?disco=AAAAgmxN6Bw))

**Comment by aefhm** [comment]
😅 I think this was intended to capture that some query params were not actively used, but the case for at least `ORDER` was addressed https://github.com/oasisprotocol/oasis-indexer/pull/110.

**Comment by aefhm** [comment]
Let's just repurpose this for future pagination improvements.

I do think we should be more clear or precise with the implied order of the returned data unless we want to just go with `height`.

**Comment by mitjat** [comment]
Short-term goal: Get input from Product whether we should sink time into this, or commit to living with `offset`-based pagination in the long run. Have them understand that switching later (once UI is built) will cost at least twice as much.

**Comment by mitjat** [comment]
https://app.clickup.com/t/3t22jx5

**Comment by ptrus** [comment]
> Looks unlikely we'll pursue this. Closing at least for now.
